# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fav_limit <- function(twitter_data_filtered) {
    .Call('_TwitterMoodUSA_fav_limit', PACKAGE = 'TwitterMoodUSA', twitter_data_filtered)
}

