// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fav_limit
NumericVector fav_limit(NumericVector twitter_data_filtered);
RcppExport SEXP _TwitterMoodUSA_fav_limit(SEXP twitter_data_filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type twitter_data_filtered(twitter_data_filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(fav_limit(twitter_data_filtered));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TwitterMoodUSA_fav_limit", (DL_FUNC) &_TwitterMoodUSA_fav_limit, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_TwitterMoodUSA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
